### ISSUE TITLE
Spirits stopping PK from enabling?

### ISSUE THREAD

**Issue by Absentt** [PrideInt/Spirits-The-Complete-Set#4]
Hiiii, 

We're on 1.15.2 using PK 1.8.9 and we're getting this error with Spirits, specifically "Infest"

https://pastebin.com/JmC7D4sG

Not sure what to dooooo about it

**Comment by PrideInt** [comment]
sorry i didnt create Spirits, you need to contact xNuminousx or Numin about
this issue. i only developed the Spirits Set, which doesn't seem to be
causing any issues

**Comment by Absentt** [comment]
We don't have https://projectkorra.com/forum/resources/spirits.323/ ;-;

I'm assuming we need that for it to work? xD
